name: magiceye
description: An abstraction on top of flutter camera, that allows you to have a default camera screen or build your own with the layer builders.
version: 0.1.4
homepage: https://github.com/mateusfccp/magiceye
repository: https://github.com/mateusfccp/magiceye

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  camera: ^0.5.7+3
  dartz: ^0.8.9
  flutter:
    sdk: flutter
  path_provider: ^1.5.1
  native_device_orientation: ^0.3.0
  rxdart: ^0.24.0

dev_dependencies:
  test: ^1.9.4
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  plugin:
    androidPackage: me.mateusfccp.magiceye
    pluginClass: MagicEyePlugin
