name: magiceye
description: An abstraction on top of flutter camera, that allows you to have a default camera screen or build your own with the layer builders.
version: 0.1.7+1
homepage: https://github.com/mateusfccp/magiceye
repository: https://github.com/mateusfccp/magiceye

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.5.3 <3.0.0"

dependencies:
  camera: ^0.9.2+2
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  path_provider: ^2.0.4
  native_device_orientation: ^1.0.0
  rxdart: ^0.26.0

dev_dependencies:
  test: ^1.14.4
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  plugin:
      platforms:
        package: me.mateusfccp.magiceye
        pluginClass: MagicEyePlugin
