name: magiceye
description: An abstraction on top of flutter camera, that allows you to have a default camera screen or build your own with the layer builders.
version: 0.2.0-dev.0
homepage: https://github.com/mateusfccp/magiceye
repository: https://github.com/mateusfccp/magiceye

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  camera: ^0.5.8+2
  dartz: ^0.9.1
  flutter:
    sdk: flutter
  rxdart: ^0.24.1

dev_dependencies:
  test: ^1.14.4
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  plugin:
    androidPackage: me.mateusfccp.magiceye
    pluginClass: MagicEyePlugin
